### ISSUE TITLE
Questionnaire matching query does not exist error

### ISSUE THREAD

**Issue by twinkarma** [RSE-Sheffield/SORT#22]
I get this error when signing up as a new user. Looks like the view is trying to get a questionnaire for the user that doesn't exist.

![Image](https://github.com/user-attachments/assets/a1fcbad0-f3ae-49e2-a9c1-266251d47869)

**Comment by f-allian** [comment]
@twinkarma This error happens because you won't have made your migrations and the questionnaires/surveys don't exist in your database. The questions/questionnaires are backed up in `/data` as `.json` files. To avoid this, run the following:

1. `python manage.py loaddata questions.json` to load the questions and `python manage.py loaddata questionnaires.json`
2. `python manage.py makemigrations`
3. `python manage.py migrate`

and the questions will be loaded into the database without any errors.
